import fs from 'fs';
import path from 'path';

const INIT_CODE_PLACEHOLDER = /{{MINIFIED_INIT_CODE}}/g;
const FUNCTION_NAME_PLACEHOLDER = /{{FUNCTION_NAME}}/g;

/**
 * This script generates the ../output/demo.html file, by filling in the template.html file with
 * the code generated by webpack, in ../output/init.js.
 */

const args = process.argv;
if (args.length < 3) {
  console.log(`Usage: babel-node generate_demo.js functionName`);
  process.exit(-1);
}
const functionName = args[2];
console.log('Generating a demo file at output/demo.html, using this tracking function name: ', functionName);

const initJs = fs.readFileSync(path.resolve(__dirname, '../output/init.js'), 'utf8');
const templateHtml = fs.readFileSync(path.resolve(__dirname, './html/template.html'), 'utf-8');

const html = templateHtml
    .replace(INIT_CODE_PLACEHOLDER, initJs)
    .replace(FUNCTION_NAME_PLACEHOLDER, functionName);

fs.writeFileSync(path.resolve(__dirname, '../output/demo.html'), html);
